### ISSUE TITLE
No install target

### ISSUE THREAD

**Issue by MarekPikula** [unruhschuh/MrWriter#2]
`make install` does nothing – it should install MrWriter binary automatically.

**Comment by unruhschuh** [comment]
Copied from our discussion on Kournal/Kournal gitter:

> MrWriter requires Qt 5.5.1, since there is a Bug in the previous versions, such that the events "QEvent::TabletEnterProximity" and "QEvent::TabletLeaveProximity" don't occur. There is also this bug: https://bugreports.qt.io/browse/QTBUG-47007. Those two bugs together make the disctinction between mouse and tablet events impossible (at least I don't have a solution, and I don't need one, since the first bug was fixed in 5.5.1).

`make install` would therefore only make sense on systems that have Qt 5.5.1 installed as shared library. I don't think that is the case for most Linux distributions, hence the AppImage and the Qt 5.5.1 library bundled tar.gz in the releases.

There is probably a workaround for the bugs mentioned above, so that MrWriter would work with older versions of Qt. My motivation to find one is rather low, since I'm happy with the AppImage approach (thus far). If anyone wants to fix it, I'll be happy to pull.

**Comment by MarekPikula** [comment]
As I'm making ebuild for Gentoo it's possible to add Qt 5.6 dependency.

**Comment by unruhschuh** [comment]
Do you need `make install` for making the ebuild?

I'm just adding the following link, in order to find it once I come around to fixing this.
http://doc.qt.io/qt-5/qmake-advanced-usage.html#installing-files

**Comment by MarekPikula** [comment]
No I don't. I can just `dobin`, but it'd be nice to include it in future in QMake script.

**Comment by unruhschuh** [comment]
There is an install target now so I'm closing this.
